### ISSUE TITLE
Feature request: Conform to WebStorage API in order to be used as a drop-in replacement for e.g localforage  

### ISSUE THREAD

**Issue by flipace** [jepiqueau/capacitor-data-storage-sqlite#14] opened 2019-11-13 01:08 UTC
If this plugin would adhere to the `Storage` API (https://developer.mozilla.org/de/docs/Web/API/Storage) it would be possible to use it as a drop-in replacement for libraries such as `redux-persist` which depend on the functions `getItem`, `setItem`,  `removeItem`, `getAllKeys`.

In our app, we're probably going to wrap this plugin somewhat like this for the time being:

```
storage = {
    getAllKeys: cb => { CapacitorDataStorageSqlite.keys().then(keys => cb(null, keys)); },
    getItem: (key, cb) => { CapacitorDataStorageSqlite.get({ key }).then(value => cb(null, value)); },
    setItem: (key, value, cb) => { CapacitorDataStorageSqlite.get({ key, value }).then(() => cb()); },
    removeItem: (key, cb) => { CapacitorDataStorageSqlite.remove({ key }).then(() => cb()); },
};
```

*EDIT:* I just found that in https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/4 someone else is trying a similar thing. In case you don't want to change the api of CapacitorDataStorage, feel free to close this.

**Comment by jepiqueau** [comment] 2019-11-13 10:48
@flipace 
Can you confirm that your wrapper is what it is above or 
storage = {
    getAllKeys: cb => { CapacitorDataStorageSqlite.keys().then(keys => cb(null, keys.keys)); },
    getItem: (key, cb) => { CapacitorDataStorageSqlite.get({ key }).then(value => cb(null, value.value)); },
    setItem: (key, value, cb) => { CapacitorDataStorageSqlite.get({ key, value }).then(() => cb()); },
    removeItem: (key, cb) => { CapacitorDataStorageSqlite.remove({ key }).then(() => cb()); },
};
in your case the gatAllKeys will return {keys:["key1","key2",...]} in my case it will return an Array ["key1","key2",...]
i could add these functions to the interface and keeping the others for consistency with old releases

**Comment by flipace** [comment] 2019-11-14 20:12
@jepiqueau the following is what we ended up with eventually - our qa team is going to perform some testing tomorrow to ensure everything works smooth.

```js
/**
 * Creates a custom storage engine utilizing
 * [capacitor-data-storage-sqlite](https://github.com/jepiqueau/capacitor-data-storage-sqlite)
 * which stores data in a SQLite database.
 */
export default function createCapacitorSqliteStorage() {
  const { CapacitorDataStorageSqlite } = Plugins;

  return {
    getAllKeys: cb => {
      CapacitorDataStorageSqlite.keys()
        .then(({ keys }) => cb(null, keys))
        .catch(cb);
    },
    getItem: (key, cb) => {
      CapacitorDataStorageSqlite.get({ key })
        .then(({ value }) => cb(null, value))
        .catch(cb);
    },
    setItem: (key, value, cb) => {
      CapacitorDataStorageSqlite.set({ key, value })
        .then(() => cb())
        .catch(cb);
    },
    removeItem: (key, cb) => {
      CapacitorDataStorageSqlite.remove({ key })
        .then(() => cb())
        .catch(cb);
    },
  };
}
```

**Comment by jepiqueau** [comment] 2019-11-17 17:25
@flipace  with the new release of capacitor-data-storage-sqlite allowing for customization of the database name and table name or multiple tables you will have to add in your wrapper the following :

```
      openStore: (options,cb) => {
          storage.openStore(options)
          .then(({result} ) => cb(null, result))
          .catch(cb);
      },
      setTable: (table, cb) => {
        storage.setTable(table)
        .then(({result,message} ) => cb(null, result,message))
        .catch(cb);
      },
```

**Comment by jepiqueau** [comment] 2019-11-17 19:30
@flipace i have added the javascript and typescript wrappers in the README of the capacitor-data-storage-sqlite capacitor plugin. So if it works for you, i will close the issue.

**Comment by flipace** [comment] 2019-11-17 20:01
@jepiqueau thanks for the update -> I should be able to check it out tomorrow and will let you know how it goes! Thanks a lot for your effort!

**Comment by jepiqueau** [comment] 2020-01-08 17:26
This has been implemented

**Closed by jepiqueau** 2020-01-08 17:26 UTC

**Comment by asgeo1** [comment] 2020-04-20 13:11
I tried out the `StorageAPIWrapper` class, but found that it didn't work out of the box when hydrating data.

The problem is that `redux-persist` will call `storage.getItem` when hydrating, but at that point `StorageAPIWrapper.openStore` has not been called, so there's nothing to hydrate and throws an error.

I couldn't figure out a way to call `StorageAPIWrapper.openStore` prior to calling creating my store, since it's async.

So I changed the wrapper class to the following, and now it works:

```
import { Plugins } from "@capacitor/core";
import * as CapacitorSQLPlugin from "capacitor-data-storage-sqlite";

const { CapacitorDataStorageSqlite, Device } = Plugins;

export class StorageAPIWrapper {
  public storage: any = {};
  private opened: boolean = false

  async init(): Promise<void> {
    const info = await Device.getInfo();

    console.log("platform ", info.platform);

    if (info.platform === "ios" || info.platform === "android") {
      this.storage = CapacitorDataStorageSqlite;
    } else {
      this.storage = CapacitorSQLPlugin.CapacitorDataStorageSqlite;
    }
  }

  public async openStore(options: any): Promise<boolean> {
    await this.init();
    const { result } = await this.storage.openStore(options);
    this.opened = true
    return result;
  }

  public async setTable(table: any): Promise<any> {
    const { result, message } = await this.storage.setTable(table);
    return Promise.resolve([result, message]);
  }

  public async setItem(key: string, value: string): Promise<void> {
    if (!this.opened) { await this.openStore({}) }
    await this.storage.set({ key, value });
    return;
  }

  public async getItem(key: string): Promise<string> {
    if (!this.opened) { await this.openStore({}) }
    const { value } = await this.storage.get({ key });
    return value;
  }

  public async getAllKeys(): Promise<Array<string>> {
    if (!this.opened) { await this.openStore({}) }
    const { keys } = await this.storage.keys();
    return keys;
  }

  public async removeItem(key: string): Promise<void> {
    if (!this.opened) { await this.openStore({}) }
    await this.storage.remove({ key });
    return;
  }

  public async clear(): Promise<void> {
    if (!this.opened) { await this.openStore({}) }
    await this.storage.clear();
    return;
  }

  public async deleteStore(options: any): Promise<boolean> {
    await this.init();
    const { result } = await this.storage.deleteStore(options);
    return result;
  }
}
```

If there's a better way, let me know

**Comment by jepiqueau** [comment] 2020-04-21 05:45
@asgeo1 First thanks for using the plugin and for your comment. The wrapper was given as an example to conform to the storage API. I do not know enough about redux-persist, so i do not have any problem with what you suggested. Nevertheless, I wonder why you cannot open the store in your app before redux-persist will call storage.getItem, which framework are you using? At the end what is important is that you find a way to make usage of the plugin. if you have a small app with redux showing the problem, store it on github and i will have a look

**Comment by asgeo1** [comment] 2020-04-21 06:25
Hi @jepiqueau, I'm using `redux-persist` alongside `redux-toolkit`.

I basically have code that looks like this:

```
// src/app/store.ts

import { configureStore, getDefaultMiddleware } from "@reduxjs/toolkit";
import {
  persistStore,
  persistReducer,
  PERSIST,
} from "redux-persist";

import { StorageAPIWrapper } from './storage-api-wrapper'
import rootReducer from "./root-reducer";

const storage = new StorageAPIWrapper()
storage.openStore({})

const persistConfig = {
  key: "root",
  version: 1,
  storage
}

const persistedReducer = persistReducer(persistConfig, rootReducer);

export const store = configureStore({
  reducer: persistedReducer,
  middleware: getDefaultMiddleware({
    serializableCheck: {
      ignoredActions: [PERSIST]  // Needed so redux-persist will work with redux-toolkit
    }
  })
});

export const persistor = persistStore(store);

if (process.env.NODE_ENV === "development" && module.hot) {
  module.hot.accept("./root-reducer", () => {
    const newRootReducer = require("./root-reducer").default;
    store.replaceReducer(persistReducer(persistConfig, newRootReducer));
  });
}

export type AppDispatch = typeof store.dispatch;
export default store;
```

So I do call `openStore()` before I setup the store with `redux-persist` / `redux-toolkit`.  But because `openStore` is async, the timing is wrong.   It will execute `configureStore` before `openStore` has finished running, triggering an error.

I'm sure there's a way to `await` or something, but I wasn't sure how that would work in this context.

But yes, the mods I made fix the issue I was having. Might be useful for anyone else having the same issue.

Thanks for responding!

**Comment by jepiqueau** [comment] 2020-04-22 07:44
@asgeo1 i am looking at it, can you share the code of the StorageAPIWrapper you are using as i have made so much changes that i do not know the one referenced by ` import { StorageAPIWrapper } from './storage-api-wrapper'`

**Comment by asgeo1** [comment] 2020-04-22 08:05
Hi @jepiqueau, cool thanks. My version of `StorageAPIWrapper` is the same as what I put in my first comment - https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/14#issuecomment-616543039

**Comment by jepiqueau** [comment] 2020-04-22 08:11
@asgeo1 sorry you already give it

**Comment by jepiqueau** [comment] 2020-04-22 08:20
@asgeo1
can you provide the code for rootReducer

**Comment by asgeo1** [comment] 2020-04-22 08:23
Sure, I have this:

```
import { combineReducers } from '@reduxjs/toolkit'
import toolbarReducer from '../components/toolbar/toolbar-reducer'

const rootReducer = combineReducers({
  toolbar: toolbarReducer
})

export type RootState = ReturnType<typeof rootReducer>
export default rootReducer
```

You'd have to change `toolbar-reducer` to whatever your case is though

**Comment by jepiqueau** [comment] 2020-04-22 15:14
@asgeo1 There is no way as the <Provider store={store}> is hydrated first in the app process.
in the store.ts file you defined only 
```
const storage = new StorageAPIWrapper()
```
it can also be if you want to specified the database name and table name
``` 
const storage = new StorageAPIWrapper("dbFoo","tableFoo") 
```

so i modified the wrapper as follows 
```
import { Plugins } from "@capacitor/core";
import * as CapacitorSQLPlugin from "capacitor-data-storage-sqlite";

const { CapacitorDataStorageSqlite, Device } = Plugins;

export class StorageAPIWrapper {
  public storage: any = {};
  private opened: boolean = false
  private _dbName: string;
  private _tableName: string;
  private _encrypted: boolean;
  private _mode: string;
  

  constructor(database?:string, table?:string, encrypted?:boolean, mode?:string) {
    this._dbName = database ? database : "";
    this._tableName = table ? table : "";
    this._encrypted = encrypted ? encrypted : false;
    this._mode = mode ? mode : "";

  }
  private async init(): Promise<void> {
    const info = await Device.getInfo();

    console.log("platform ", info.platform);

    if (info.platform === "ios" || info.platform === "android") {
      this.storage = CapacitorDataStorageSqlite;
    } else {
      this.storage = CapacitorSQLPlugin.CapacitorDataStorageSqlite;
    }
  }

  private async openStore(options: any): Promise<boolean> {
    await this.init();
    const { result } = await this.storage.openStore(options);
    this.opened = true
    return result;
  }
  private async firstCall(): Promise<boolean> {
      let options: any = {};
      if(this._dbName.length > 1) {
        options.database = this._dbName;
        if(this._tableName.length > 1) options.table = this._tableName;
      }
      if(this._encrypted) {
          options.encrypted = this._encrypted;
          options.mode = this._mode ? this._mode : "secret";
      }

      const retB: boolean = await this.openStore(options);
      if(!retB) console.log("firstCall: Error openStore failed")
      return retB;
  }
  public async setTable(table: any): Promise<any> {
    if (!this.opened) { await this.firstCall() }
    const { result, message } = await this.storage.setTable(table);
    return Promise.resolve([result, message]);
  }

  public async setItem(key: string, value: string): Promise<void> {
    if (!this.opened) { await this.firstCall() }
    await this.storage.set({ key, value });
    return;
  }

  public async getItem(key: string): Promise<string> {
    if (!this.opened) { await this.firstCall() }
    const { value } = await this.storage.get({ key });
    return value;
  }

  public async getAllKeys(): Promise<Array<string>> {
    if (!this.opened) { await this.firstCall() }
    const { keys } = await this.storage.keys();
    return keys;
  }

  public async removeItem(key: string): Promise<void> {
    if (!this.opened) { await this.firstCall() }
    await this.storage.remove({ key });
    return;
  }

  public async clear(): Promise<void> {
    if (!this.opened) { await this.firstCall() }
    await this.storage.clear();
    return;
  }

  public async deleteStore(options: any): Promise<boolean> {
    if (!this.opened) { await this.firstCall() }
    const { result } = await this.storage.deleteStore(options);
    return result;
  }
}
```
This should work

**Comment by asgeo1** [comment] 2020-04-23 00:25
Yeah cool, that works well 👍

**Comment by jepiqueau** [comment] 2020-04-23 06:15
@asgeo1 Ok you are welcome
