### ISSUE TITLE
How frequently should I call closeStore?

### ISSUE THREAD

**Issue by garbit** [jepiqueau/capacitor-data-storage-sqlite#51] opened 2021-09-06 15:17 UTC
Hi there,

I'm using Vue + Vuex actions on iOS to query the db. These actions typically look like the following:

```javascript
import { CapacitorDataStorageSqlite, capOpenStorageOptions} from "capacitor-data-storage-sqlite";
import { Capacitor } from '@capacitor/core';

async [ACTIONS.GET_MEDIA](store, filename: string) {
    const options: capOpenStorageOptions = {
      database: dbName,
      table: TABLES.MEDIA
    }
    
    let result = undefined
    const sqlStore = CapacitorDataStorageSqlite
    
    try {
      await sqlStore.openStore(options)
      console.log('filename:', filename)
      const media = await sqlStore.get({ key: filename})
      console.log('filename:', media.value)
      console.log('DB: GETTING VALUE', media)
      result = JSON.parse(media.value) as MediaObject
    } catch (err) {
      console.log(err)
    } finally {
      if(Capacitor.getPlatform() != 'web') {
         await sqlStore.closeStore({database: dbName})
       }
    }
    return result
  },
```

How frequently should I be calling ```.closeStore({options})```?

Currently with the ```sqlStore.closeStore``` I'm getting the following error:
```
CapacitorDataStoreageSqlite.set
{errorMessage: "set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.)", message: "set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.)"}
```

**Comment by jepiqueau** [comment] 2021-09-07 13:25
@garbit I do not know Vuex actions. For me if you open a store in an action you should close it also. Or may you can split your action in 3 actions one open the store, one doing the stuff and one closing the store. In that case you may have another action doing another stuff  but may be i am wrong

**Comment by jepiqueau** [comment] 2021-09-09 11:47
@garbit Is my answer was helpful or did you find your way. Opening and closing a store is time consuming so if you can avoid to do it when not required it would be beneficial. Feel free to close this as it is not really an issue

**Comment by garbit** [comment] 2021-09-11 15:57
This appears to be a bug. I'm opening and closing after each operation and for larger operations (with multiple inserts) I'm finding that my DB on iOS keeps erroring with:
```
set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.
```

I can't seem to get around the db eventually causing this error.

**Comment by jepiqueau** [comment] 2021-09-11 16:27
@garbit can you share your code or make a smaller code reproducing the error and share it

**Comment by garbit** [comment] 2021-09-11 17:15
I've created an example app that includes the vuex store (src/store/index.ts) for interfacing with the sqlite db. You'll need to add ios to the project and set your team credentials so that you can run the code on a native iOS device.

1. Clone repo [https://github.com/garbit/capacitor-data-storage-sqlite-debug-project](https://github.com/garbit/capacitor-data-storage-sqlite-debug-project)
2. npm i
3. ionic capacitor add ios
4. ionic capacitor open ios
5. Set your signing details (select the project browser (folder on top left) > Select App > Navigate to Signing & Capabilities > Add your team info)
6. npm run ios-serve
7. Observe the output in Safari debug tools with the following error:
```
set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.
```

[https://github.com/garbit/capacitor-data-storage-sqlite-debug-project](https://github.com/garbit/capacitor-data-storage-sqlite-debug-project)

**Comment by garbit** [comment] 2021-09-11 17:24
For confirmation - this issue only appears in iOS. When working in a web browser this issue does not appear.

**Comment by garbit** [comment] 2021-09-12 01:59
The error ```set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.``` specifically occurs after I perform lots of writes and then call close straight afterwards. When I don't close the db I don't have an issue.

Is the await on the ```.set``` not actually fully completing the entire write to db before the promise is resolved?

**Comment by jepiqueau** [comment] 2021-09-12 09:57
@garbit I am working on it what i found right now:
- you should not have `await store.dispatch(ACTIONS.SELECT_ALL_TAGS)` in App.vue as you have it in TestView.vue ` onIonWillEnter` this was creating a RC: 21 on close as you add to times open the store and close it twice so the second time it cannot close it as it is already close.
- to see it replace in all your actions the finally block with
```
    } finally {
      if(Capacitor.getPlatform() != 'web') {
        try {
          await sqlStore.closeStore({database: dbName})
        } catch (err) {
          successful = false;
          console.log('DB: FAILED SELECT_ALL_TAGS Close', err)
        }
      }
    }
```
the successful = false; should sometimes being replace by result = undefined
- Now the code is `DB: SUCCESS INSERTING MEDIA` for a while and then get 
```
ERROR MESSAGE:  {"message":"set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.)","errorMessage":"set: The operation couldn’t be completed. ```
I suggest that you write your actions in a way that when an error occurs the code stop running and display the message. The RC: 5 means `The database file is locked`
in fact in `ACTIONS.INSERT_MEDIA_OBJECTS` i removed `const keyTest = await sqlStore.iskey({ key: media.name })` as this is done in set command of the CapacitorDataStorageSqlite plugin to decide for an INSERT or an UPDATE.
And everything works find since then. I made a PR in your https://github.com/garbit/capacitor-data-storage-sqlite-debug-project 
Voilà
feel free to close the issue if it is working on your side

**Comment by garbit** [comment] 2021-09-12 10:32
Thank you for taking a look at the codebase. It's very much appreciated. I had a couple of questions:

"you should not have await store.dispatch(ACTIONS.SELECT_ALL_TAGS) in App.vue as you have it in TestView.vue onIonWillEnter this was creating a RC: 21 on close as you add to times open the store and close it twice so the second time it cannot close it as it is already close."

I noticed I was doing the SELECT_ALL_TAGS on App.vue and had this commented out whilst I was playing around last night but didn't commit this - my apologies. If I did need to perform that action to initialize the app, how and where would be best to do this?

"to see it replace in all your actions the finally block with"
- I'll replace the codeblocks with the try catch as you have suggested (including the result = undefined in places).

RROR MESSAGE:  {"message":"set: The operation couldn’t be completed. (CapacitorDataStorageSqlite.StorageHelperError error 5.)","errorMessage":"set: The operation couldn’t be completed. ```
I suggest that you write your actions in a way that when an error occurs the code stop running and display the message. The RC: 5 means `The database file is locked`

"in fact in `ACTIONS.INSERT_MEDIA_OBJECTS` i removed `const keyTest = await sqlStore.iskey({ key: media.name })` as this is done in set command of the CapacitorDataStorageSqlite plugin to decide for an INSERT or an UPDATE."
- This should really be in the docs as it's not clear currently. How sure are you that this is the case? I must not overwrite the existing data as this insert will be called multiple times on launch.

"And everything works find since then. I made a PR in your https://github.com/garbit/capacitor-data-storage-sqlite-debug-project"
- I'll take a look at this and confirm on my side. Meanwhile, thank you so far!

**Comment by garbit** [comment] 2021-09-12 12:45
I've pulled your code and have tried the new code (looks like it works). However when I try a more extreme attempt of reading/writing to the db I still get issues.

I've found that there is still an issue if you perform a block of writes, then query individual rows (worst case scenario).

See below (I'll also add this to the repo):
```
      console.log('fakeMediaObjects', fakeMediaObjects)
      // Insert into db
      await store.dispatch(ACTIONS.INSERT_MEDIA_OBJECTS, fakeMediaObjects)
      // Query all media
      const files = await store.dispatch(ACTIONS.SELECT_ALL_MEDIA)
      console.log('files', files.keysvalues)
      // Get each row from db (worst case)
      files.keysvalues.map(async (f: any) => {
        console.log('await store.dispatch(ACTIONS.GET_MEDIA, f.key)', await store.dispatch(ACTIONS.GET_MEDIA, f.key))
        // console.log('f', f)
      });
```

Errors:

```
[Error] {message: "openStore: Failed in openOrCreateDatabase open_v2 failed", errorMessage: "openStore: Failed in openOrCreateDatabase open_v2 failed"}
	(anonymous function) (user-script:2:266)
	(anonymous function) (user-script:2:208)
	(anonymous function) (user-script:2:411)
	Global Code (Script Element 175:1)

[Error] {message: "set: Error: prepareSQL finalize failed rc: 14 message: unable to open database file", errorMessage: "set: Error: prepareSQL finalize failed rc: 14 message: unable to open database file"}
	(anonymous function) (user-script:2:266)
	(anonymous function) (user-script:2:208)
	(anonymous function) (user-script:2:411)
	Global Code (Script Element 23:1)
```

**Comment by jepiqueau** [comment] 2021-09-12 12:53
@garbit 
- I tested it in Android and it works too.
- to avoid the mess with dependencies remove ios, node_modules and package-lock;json and do a 
``` 
npm install
npm run build
npx cap add ios
npx cap copy
npx cap open ios
```
What do you mean by more extreme attempt of reading/writing

If I did need to perform that action to initialize the app, how and where would be best to do this? 
i have to look at it

**Comment by jepiqueau** [comment] 2021-09-12 13:53
@garbit you can have it in the main.ts 
```
const tags = ref([] as Tag[]);
const app = createApp(App).use(store, key)
  .use(IonicVue)
  .use(router)
  .use(Vue3TouchEvents)
  .use(i18n)

app.provide('emitter', emitter)
// app.provide('i18n', i18n)

router.isReady().then(() => {
  store.dispatch(ACTIONS.SELECT_ALL_TAGS).then((res) => {
    console.log(`$$$$$ res ${JSON.stringify(res)}`)
    tags.value = res;
    app.config.globalProperties.$tags = tags;
    app.mount('#app');
  })
});```
and in TestView.vue 
```
  setup() {
    const app = getCurrentInstance();
    const tags = app?.appContext.config.globalProperties.$tags;
    const store = useStore()
//    const tags = ref([] as Tag[])
    const mediaObjects = ref([] as MediaObject[])

    onIonViewWillEnter(async () => {
      console.log("$$$ in TestView onIonViewWillEnter")
      console.log("$$$ TestView onIonViewWillEnter going to dispatch SELECT_ALL_TAGS")
//      tags.value = await store.dispatch(ACTIONS.SELECT_ALL_TAGS)
//      console.log(`$$$ tags.value ${tags.value}`)
```
it test with a loop set to 1000  and with `npm run ios-serve` this time and i got everything working

**Comment by jepiqueau** [comment] 2021-09-12 14:00
@garbit see implementation https://github.com/jepiqueau/capacitor-data-storage-sqlite-debug-project

**Comment by jepiqueau** [comment] 2021-09-12 14:20
@garbit Which simulator are you using i tested with `IPHONE 12 Pro Max`

**Comment by garbit** [comment] 2021-09-12 18:04
> @garbit
> 
>     * I tested it in Android and it works too.
> 
>     * to avoid the mess with dependencies remove ios, node_modules and package-lock;json and do a
> 
> 
> ```
> npm install
> npm run build
> npx cap add ios
> npx cap copy
> npx cap open ios
> ```
> 
> What do you mean by more extreme attempt of reading/writing
> 
> If I did need to perform that action to initialize the app, how and where would be best to do this?
> i have to look at it

The usecase of inserting 1k rows and then querying each row again to pull it back out of the database is probably the worst case scenario so I thought I'd try doing that and I received the issues I described: 

```
[Error] {message: "openStore: Failed in openOrCreateDatabase open_v2 failed", errorMessage: "openStore: Failed in openOrCreateDatabase open_v2 failed"}
	(anonymous function) (user-script:2:266)
	(anonymous function) (user-script:2:208)
	(anonymous function) (user-script:2:411)
	Global Code (Script Element 175:1)

[Error] {message: "set: Error: prepareSQL finalize failed rc: 14 message: unable to open database file", errorMessage: "set: Error: prepareSQL finalize failed rc: 14 message: unable to open database file"}
	(anonymous function) (user-script:2:266)
	(anonymous function) (user-script:2:208)
	(anonymous function) (user-script:2:411)
	Global Code (Script Element 23:1)
```

I've been running the code on an iPad Pro 11-inch 3rd Gen rather than a simulator. 

I've cloned your repo and tried to build main but I'm getting build errors, not entirely sure why:
```javascript

> capacitor-data-storage-sqlite-debug-project@0.0.3 build
> vue-cli-service build


⠙  Building for production...

 ERROR  Failed to compile with 10 errors                                                                                                                                                                                                                       18:47:52

 error  in src/App.vue:37:27

TS2305: Module '"../node_modules/vue/dist/vue"' has no exported member 'inject'.
    35 | <script lang="ts">
    36 | import { IonApp, IonRouterOutlet, IonContent, IonHeader, IonTitle, IonToolbar, IonListHeader, IonItem, IonMenuToggle, IonList, IonMenu, IonButton, IonLabel, menuController, onIonViewWillEnter } from '@ionic/vue'
  > 37 | import { defineComponent, inject, computed, watch, ref, onMounted, getCurrentInstance } from 'vue';
       |                           ^^^^^^
    38 | import { useStore, MUTATIONS, ACTIONS, TABLES, Tag, MediaMetadata} from './store'
    39 | import { useRouter, useRoute } from 'vue-router'
    40 | import { useI18n } from 'vue-i18n'

 error  in src/App.vue:37:45

TS2305: Module '"../node_modules/vue/dist/vue"' has no exported member 'watch'.
    35 | <script lang="ts">
    36 | import { IonApp, IonRouterOutlet, IonContent, IonHeader, IonTitle, IonToolbar, IonListHeader, IonItem, IonMenuToggle, IonList, IonMenu, IonButton, IonLabel, menuController, onIonViewWillEnter } from '@ionic/vue'
  > 37 | import { defineComponent, inject, computed, watch, ref, onMounted, getCurrentInstance } from 'vue';
       |                                             ^^^^^
    38 | import { useStore, MUTATIONS, ACTIONS, TABLES, Tag, MediaMetadata} from './store'
    39 | import { useRouter, useRoute } from 'vue-router'
    40 | import { useI18n } from 'vue-i18n'

 error  in src/App.vue:37:52

TS2305: Module '"../node_modules/vue/dist/vue"' has no exported member 'ref'.
    35 | <script lang="ts">
    36 | import { IonApp, IonRouterOutlet, IonContent, IonHeader, IonTitle, IonToolbar, IonListHeader, IonItem, IonMenuToggle, IonList, IonMenu, IonButton, IonLabel, menuController, onIonViewWillEnter } from '@ionic/vue'
  > 37 | import { defineComponent, inject, computed, watch, ref, onMounted, getCurrentInstance } from 'vue';
       |                                                    ^^^
    38 | import { useStore, MUTATIONS, ACTIONS, TABLES, Tag, MediaMetadata} from './store'
    39 | import { useRouter, useRoute } from 'vue-router'
    40 | import { useI18n } from 'vue-i18n'

 error  in src/App.vue:37:57

TS2305: Module '"../node_modules/vue/dist/vue"' has no exported member 'onMounted'.
    35 | <script lang="ts">
    36 | import { IonApp, IonRouterOutlet, IonContent, IonHeader, IonTitle, IonToolbar, IonListHeader, IonItem, IonMenuToggle, IonList, IonMenu, IonButton, IonLabel, menuController, onIonViewWillEnter } from '@ionic/vue'
  > 37 | import { defineComponent, inject, computed, watch, ref, onMounted, getCurrentInstance } from 'vue';
       |                                                         ^^^^^^^^^
    38 | import { useStore, MUTATIONS, ACTIONS, TABLES, Tag, MediaMetadata} from './store'
    39 | import { useRouter, useRoute } from 'vue-router'
    40 | import { useI18n } from 'vue-i18n'

 error  in src/App.vue:37:68

TS2305: Module '"../node_modules/vue/dist/vue"' has no exported member 'getCurrentInstance'.
    35 | <script lang="ts">
    36 | import { IonApp, IonRouterOutlet, IonContent, IonHeader, IonTitle, IonToolbar, IonListHeader, IonItem, IonMenuToggle, IonList, IonMenu, IonButton, IonLabel, menuController, onIonViewWillEnter } from '@ionic/vue'
  > 37 | import { defineComponent, inject, computed, watch, ref, onMounted, getCurrentInstance } from 'vue';
       |                                                                    ^^^^^^^^^^^^^^^^^^
    38 | import { useStore, MUTATIONS, ACTIONS, TABLES, Tag, MediaMetadata} from './store'
    39 | import { useRouter, useRoute } from 'vue-router'
    40 | import { useI18n } from 'vue-i18n'

 error  in src/components/PageHeader.vue:19:27

TS2305: Module '"@vue/runtime-core"' has no exported member 'inject'.
    17 | <script lang="ts">
    18 | import { IonHeader, IonToolbar, IonTitle, IonButtons, IonMenuToggle, IonButton } from '@ionic/vue'
  > 19 | import { defineComponent, inject } from '@vue/runtime-core'
       |                           ^^^^^^
    20 | import IosMenuIcon from 'vue-ionicons/dist/ios-menu.vue'
    21 |
    22 | export default defineComponent({

 error  in src/main.ts:1:21

TS2305: Module '"../node_modules/vue/dist/vue"' has no exported member 'ref'.
  > 1 | import { createApp, ref,  } from 'vue'
      |                     ^^^
    2 | import App from './App.vue'
    3 | import router from './router';
    4 | import { store, key, Tag, ACTIONS } from './store'

 error  in src/store/index.ts:1:10

TS2305: Module '"../../node_modules/vue/dist/vue"' has no exported member 'InjectionKey'.
  > 1 | import { InjectionKey } from 'vue'
      |          ^^^^^^^^^^^^
    2 | import { createStore, useStore as baseUseStore, Store, MutationTree, ActionTree } from 'vuex'
    3 | import { CapacitorDataStorageSqlite, capOpenStorageOptions} from "capacitor-data-storage-sqlite";
    4 | import { mockTags } from '@/mock/tags'

 error  in src/views/TestView.vue:23:27

TS2305: Module '"../../node_modules/vue/dist/vue"' has no exported member 'ref'.
    21 | <script lang="ts">
    22 | import { IonPage, IonContent, onIonViewWillEnter } from '@ionic/vue'
  > 23 | import { defineComponent, ref, getCurrentInstance } from 'vue'
       |                           ^^^
    24 | import { useStore, ACTIONS, Tag, MediaObject, TagContributor, MediaMetadata, MediaFileType} from '../store'
    25 | import PageHeader from '@/components/PageHeader.vue'
    26 | // import dbData from '@/mock/meta-data.json'

 error  in src/views/TestView.vue:23:32

TS2305: Module '"../../node_modules/vue/dist/vue"' has no exported member 'getCurrentInstance'.
    21 | <script lang="ts">
    22 | import { IonPage, IonContent, onIonViewWillEnter } from '@ionic/vue'
  > 23 | import { defineComponent, ref, getCurrentInstance } from 'vue'
       |                                ^^^^^^^^^^^^^^^^^^
    24 | import { useStore, ACTIONS, Tag, MediaObject, TagContributor, MediaMetadata, MediaFileType} from '../store'
    25 | import PageHeader from '@/components/PageHeader.vue'
    26 | // import dbData from '@/mock/meta-data.json'
```

**Comment by jepiqueau** [comment] 2021-09-13 05:43
@garbit tell me what you do? 
if you did this it should work
```
git clone https://github.com/jepiqueau/capacitor-data-storage-sqlite-debug-project.git
cd capacitor-data-storage-sqlite-debug-project
npm install
npm run build
npx cap sync
npm run build
npx cap copy
npx cap open ios
```

**Comment by jepiqueau** [comment] 2021-09-13 13:43
@garbit i assume you are using `yarn` and `yarn build`. in that case  i got the errors like you. I am not too much familiar with yarn i may have a look

**Comment by jepiqueau** [comment] 2021-09-16 10:03
@garbit No news from you

**Comment by garbit** [comment] 2021-09-16 12:29
Hi jepiqueau I'm using ```npm``` to manage the packages and I suspect that there has been some corruption of the dependancies. 

As I was on a tight deadline I was unable to continue using this package and have swapped out my database tooling to use [@ionic/storage](https://github.com/ionic-team/ionic-storage) offical and the associated [localForage-cordovaSQLiteDriver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver) which seems to have better performance and also free from any read/write issues that I experienced using this package.

**Comment by jepiqueau** [comment] 2021-09-16 13:06
@garbit I am sorry for this, good luck I am then closing the issue

**Closed** 2021-09-16 13:06 UTC

**Comment by garbit** [comment] 2021-09-16 13:07
Thanks you for your help so far. Let me know if I can assist in finding the performance related bug in the package.
